version: "3.8"
services:
  backend:
    image: ghcr.io/matienzo01/bot-discord:latest
    env_file:
      - ~/bot-discord.env
      ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    deploy:
      replicas: 1
      restart_policy:
        condition: none