# Usar imagen base de Node.js
FROM node:22

# Establecer directorio de trabajo
WORKDIR /app

# Copiar solo los archivos relevantes para instalar dependencias
COPY package.json pnpm-lock.yaml ./

# Instalar dependencias
RUN npm install -g pnpm
RUN pnpm install

# Copiar el código fuente al contenedor
COPY . .

# Expone el puerto de la aplicación
EXPOSE 3000

# Comando para ejecutar en el contenedor
CMD ["pnpm", "dev"]
