version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod  # Especificamos el Dockerfile para producción
    image: ghcr.io/tu_usuario/discord-backend-app:latest  # La imagen se sube a GitHub Container Registry
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure