version: "3.8"
services:
  backend:
    image: ghcr.io/matienzo01/bot-discord:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - API_TOKEN=${API_TOKEN}
    deploy:
      replicas: 1
      restart_policy:
        condition: none