name: Build and Deploy Docker Stack

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Iniciar sesión en GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construir y subir imagen
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: Dockerfile.prod
          tags: |
            ghcr.io/matienzo01/bot-discord:latest
            ghcr.io/matienzo01/bot-discord:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Crear .env
        run: |
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" > .env
          echo "API_TOKEN=${{ secrets.API_TOKEN }}" >> .env

      - name: Desplegar en servidor remoto
        uses: cssnr/stack-deploy-action@v1
        with:
          name: bot-discord
          file: docker-compose.stack.yml
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          ssh_key: ${{ secrets.REMOTE_SSH_KEY }}
          registry_auth: true
          env_file: .env
